spring:
  datasource:
    url: jdbc:h2:mem:memDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher